sudo: false
language: python
matrix:
  include:
  - os: osx
    osx_image: xcode11.2
    language: shell
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl; fi
  - if [$TRAVIS_OS_NAME = osx ]; then python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"; fi
  - chmod a+x travis.sh

install:
#  - travis.sh pip install pip-accel
  - ./travis.sh pip install -U setuptools
  - ./travis.sh pip install coveralls
script:
#  - scripts/travis.sh make check
  - ./travis.sh which python3
  - ./travis.sh python -c "import serial;s=serial.Serial('/dev/ptyp0');print(s); s.close()"; 
after_success:
  - echo Done!!!
branches:
  except:
    - /^[0-9]/
